set shell := ["bash", "-c"]

wget := require("wget")
dpkg_query := require("dpkg-query")
ldd := require("ldd")
git := require("git")
gcc := require("g++")
patchelf := require("patchelf")
tool_dir := absolute_path("tools")
src_dir := absolute_path("src")
appimagetool := tool_dir + "/appimagetool"
aria2c := tool_dir + "/aria2c"
busybox := tool_dir + "/busybox"
config_file := absolute_path("config.json")
cache_dir := absolute_path(".cache")
imgui_version := "v1.92.2b-docking"

@default:
    just --list

create-appimage config-name="xivlauncher": extract-appimagetool (download config-name)
    #!/usr/bin/env ruby
    require "fileutils"; include FileUtils
    require "pathname"

    CONFIG_NAME = "{{ config-name }}"

    class String
      def relative_to(resolve)
        Pathname.new(self).relative_path_from(resolve).to_s
      end
    end

    def gcv(key, optional=false)
      str = `just get-config-value #{CONFIG_NAME} #{key}` rescue nil
      if str.is_a?(String) && !str.empty?
        return str.strip
      end
      raise StandardError, "no key '#{key}' found for config #{CONFIG_NAME}" unless optional
      nil
    end

    def set_rpath(obj, rpath)
      puts "set_rpath (#{obj}): #{rpath}"
      `{{ patchelf }} --set-rpath "#{rpath}" "#{obj}"`
    end

    XIVLAUNCHER_EXEC_NAME = gcv("executable")
    XIVLAUNCHER_VERSION = gcv("version")
    XIVLAUNCHER_SOURCE = gcv("src")
    XIVLAUNCHER_NAME = gcv("name")
    XIVLAUNCHER_SHORT_NAME = gcv("short_name")
    XIVLAUNCHER_DESC = gcv("description")
    XIVLAUNCHER_RELEASE_TYPE = gcv("release_type")
    XIVLAUNCHER_PACKAGES = gcv("packages", true)&.split(";").map(&:strip) || []
    XIVLAUNCHER_REMOVE_FILES = gcv("remove_files", true)&.split(";").map(&:strip) || []

    APPDIR = File.join(Dir.pwd, "appdir", XIVLAUNCHER_EXEC_NAME)
    INSTALL_PATH = File.join(APPDIR, "opt", XIVLAUNCHER_EXEC_NAME)
    DESKTOP_FILE_PATH = File.join(APPDIR, "usr", "share", "applications", "#{XIVLAUNCHER_EXEC_NAME}.desktop")
    ICON_PATH = File.join(APPDIR, "usr", "share", "icons", "#{XIVLAUNCHER_EXEC_NAME}.png")
    OUTPUT_DIR = File.join(Dir.pwd, "output"); mkdir_p OUTPUT_DIR

    BINDIR = File.join(APPDIR, "usr", "bin")
    LIBDIR = File.join(APPDIR, "usr", "lib")
    EXECUTABLE_INSTALL_PATH = File.join(APPDIR, "AppRun") #File.join(BINDIR, XIVLAUNCHER_EXEC_NAME)
    BUSYBOX_INSTALL_PATH = File.join(BINDIR, "busybox")
    ARIA2C_INSTALL_PATH = File.join(BINDIR, "aria2c")

    UPDATE_DATA = "gh-releases-zsync|spiteful-fox|xivlauncher-appimage|#{XIVLAUNCHER_RELEASE_TYPE}|#{XIVLAUNCHER_NAME}-x86_64.AppImage.zsync"

    mkdir_p File.join(Dir.pwd, "appdir")
    cp_r "AppDir.template", APPDIR
    cp_r File.join(Dir.pwd, "src", "{{ config-name }}"), INSTALL_PATH
    cp File.join("resources", "xivlauncher.png"), ICON_PATH

    cp "{{ aria2c }}", ARIA2C_INSTALL_PATH
    cp "{{ busybox }}", BUSYBOX_INSTALL_PATH
    `"#{BUSYBOX_INSTALL_PATH}" --list`.split("\n").each{|e| ln_sf BUSYBOX_INSTALL_PATH.relative_to(BINDIR), File.join(BINDIR, e.strip)}


    desktop_file = File.read(File.join("resources", "xivlauncher.desktop")) % {
      name: XIVLAUNCHER_NAME,
      description: XIVLAUNCHER_DESC,
      executable: XIVLAUNCHER_EXEC_NAME,
      appimage_version: "#{`"{{ git }}" describe --tags --match "#{XIVLAUNCHER_SHORT_NAME}*"`.strip.sub("#{XIVLAUNCHER_SHORT_NAME}/", "")}"
    }
    File.write(DESKTOP_FILE_PATH, desktop_file)

    executable = File.read(File.join("resources", "xivlauncher.sh")) % {executable: XIVLAUNCHER_EXEC_NAME}
    File.write(EXECUTABLE_INSTALL_PATH, executable)
    chmod "+x", EXECUTABLE_INSTALL_PATH

    XIVLAUNCHER_REMOVE_FILES.map{|f| File.join(INSTALL_PATH, f)}.each{|f| rm_rf f}

    if XIVLAUNCHER_REMOVE_FILES.include?("cimgui.so") || XIVLAUNCHER_REMOVE_FILES.include?("ImGuiImplSDL3.so")
      `just download-imgui`
      Dir["{{ src_dir }}/_build/*.so"].each{|f| cp f, INSTALL_PATH}
    end

    [File.join(INSTALL_PATH, "XIVLauncher.Core"), Dir["#{INSTALL_PATH}/**/*.so"]].flatten.each do |obj|
      `just copy-dependencies "#{obj}" #{XIVLAUNCHER_EXEC_NAME}`
      chmod_R "+x", File.join(APPDIR, "usr", "lib")
    end


    ["libjxr-dev", "libsecret-1-dev", "libicu-dev", XIVLAUNCHER_PACKAGES].flatten.each{|l| `just copy-package-libraries #{l} #{XIVLAUNCHER_EXEC_NAME}`}

    Dir["#{LIBDIR}/*"].each{|f| set_rpath(f, "$ORIGIN")}
    Dir["#{INSTALL_PATH}/*.so"].each{|f| set_rpath(f, "$ORIGIN/../../usr/lib")}
    set_rpath(File.join(INSTALL_PATH, "XIVLauncher.Core"), "$ORIGIN/../../usr/lib")

    ln_sf DESKTOP_FILE_PATH.relative_to(APPDIR), File.join(APPDIR, "#{XIVLAUNCHER_EXEC_NAME}.desktop")
    ln_sf ICON_PATH.relative_to(APPDIR), File.join(APPDIR, "#{XIVLAUNCHER_EXEC_NAME}.png")

    `"{{ appimagetool }}.d/AppRun" -u "#{UPDATE_DATA}" "#{APPDIR}" "#{File.join(OUTPUT_DIR, XIVLAUNCHER_NAME + "-{{ arch() }}.AppImage")}"`
    Dir["*.zsync"].each{|f|mv f, OUTPUT_DIR}

copy-dependencies source-object config-name:
    #!/usr/bin/env ruby
    require "fileutils"; include FileUtils

    LIBDIR = File.join(Dir.pwd, "appdir", "{{ config-name }}", "usr", "lib")
    mkdir_p LIBDIR
    SEARCHED_FILES = []
    EXCLUDED_LIBRARIES = [
      ["c", "stdc++", "dl", "rt", "pthread", "m", "gcc_s", "z", "zstd"],
      ["wayland-client", "wayland-cursor", "wayland-egl", "wayland-server"],
      ["xcb", "xkbcommon", "X11", "X11-xcb", "Xau", "Xcursor", "Xdmcp", "Xext", "Xfixes", "Xi", "Xrandr", "Xrender", "Xss"],
      ["drm"]
    ].flatten.map{|i|"lib"+i}

    def get_deps(src)
      objects = []
      return objects if SEARCHED_FILES.include?(src)
      results = `{{ ldd }} "#{src}"`.split("\n").map{|s|s.strip}
      results.each do |r|
        matchdata = /^(.+) => (.+) \(0x[{{ HEXLOWER }}]+\)$/.match(r)
        if matchdata
          lib = matchdata.captures[1]
          objects << lib
        end
      end
      SEARCHED_FILES << src
      objects.each do |obj|
        objects |= get_deps(obj)
      end
      objects
    end

    get_deps("{{ source-object }}").each do |lib|
      destination = File.join(LIBDIR, File.basename(lib))
      exc = !EXCLUDED_LIBRARIES.select{|i| File.basename(lib).split(".")[0] == i}.empty?
      unless File.exist?(destination) || exc
        cp lib, destination
      end
    end

copy-package-libraries package-name config-name architecture="amd64":
    #!/usr/bin/env ruby
    require "fileutils"; include FileUtils

    LIBDIR = File.join(Dir.pwd, "appdir", "{{ config-name }}", "usr", "lib")

    objects = []
    `{{ dpkg_query }} -L {{ package-name }}:{{ architecture }}`.each_line do |line|
      matchdata = /^(.+\.so(\.\d)*)$/.match(line.strip)
      if matchdata
        objects << matchdata.captures[0]
      end
    end
    objects.each do |obj|
      cp "#{obj}", LIBDIR
      `just copy-dependencies "#{obj}" {{ config-name }}`
    end

download config-name:
    #!/usr/bin/env ruby
    require 'fileutils'; include FileUtils

    mkdir_p "{{ cache_dir }}"
    mkdir_p "{{ absolute_path('src') }}"
    bin_extract_dir = File.join("src", `just get-config-value {{ config-name }} executable`.strip)
    mkdir_p bin_extract_dir
    src = `just get-config-value {{ config-name }} src`.strip % {version: `just get-config-value {{ config-name }} version`.strip}
    archive_name = File.basename(src)
    dest = File.join("{{ cache_dir }}", `just get-config-value {{ config-name }} executable`.strip + ".tar.gz")
    dest_dir = dest.sub(".tar.gz", "")
    if !File.exist?(dest)
      `"{{ wget }}" -O #{dest} #{src}`
    end
    if !File.exist?(File.join(bin_extract_dir, "XIVLauncher.Core"))
      `tar -xzf "#{dest}" -C "#{bin_extract_dir}"`
    end

extract-appimagetool:
    #!/usr/bin/env bash
    set -ueox pipefail

    if [ ! -d "{{ appimagetool }}.d" ]; then
        (cd {{ tool_dir }} && "{{ appimagetool }}" --appimage-extract)
        mv "{{ tool_dir }}/squashfs-root" "{{ tool_dir }}/appimagetool.d"
    fi

download-imgui:
    #!/usr/bin/env bash
    set -ueox pipefail

    build_dir="{{ src_dir }}/_build"
    mkdir -p "{{ src_dir }}"
    mkdir -p "$build_dir"

    cflags="-DIMGUI_USE_WCHAR32=1 -DIMGUI_ENABLE_FREETYPE=1 -DIMGUI_ENABLE_STB_TRUETYPE=1 -DIMGUI_DISABLE_OBSOLETE_FUNCTIONS=1 -fPIC -shared"
    ldflags="-Wl,--no-undefined"

    cimgui_cflags="-DCIMGUI_FREETYPE=1 -DCIMGUI_VARGS0 -DIMGUI_USER_CONFIG=\"{{ src_dir }}/cimgui/cimconfig.h\" $(pkg-config --cflags freetype2) $cflags"
    cimgui_ldflags="$(pkg-config --libs freetype2) $ldflags"

    if [ ! -d "{{ src_dir }}/imgui" ]; then
        just git-clone https://github.com/ocornut/imgui {{ imgui_version }}
    fi

    if [ ! -x "$build_dir/cimgui.so" ]; then
        if [ ! -d "{{ src_dir }}/cimgui" ]; then
            just git-clone https://github.com/JunaMeinhold/cimgui docking_inter
            (cd "{{ src_dir }}/cimgui" && git checkout d61baefa0ce2a9db938ffdeb29e64f90f44cc037)
            rm -rf "{{ src_dir }}/cimgui/imgui"
            ln -s "{{ src_dir }}/imgui" "{{ src_dir }}/cimgui/imgui"
        fi
        cd "{{ src_dir }}/cimgui"
        (cd ./generator && ./generator.sh)
        "{{ gcc }}" -o "$build_dir/cimgui.so" \
        -I. -Iimgui -Iimgui/misc/freetype \
        $cimgui_cflags \
        imgui/imgui{,_draw,_widgets,_tables,_demo}.cpp \
        imgui/misc/freetype/imgui_freetype.cpp \
        {{ src_dir }}/cimgui/{cimgui,cimgui_impl}.cpp \
        $cimgui_ldflags
    fi

    cimgui_impl_cflags="-DCIMGUI_USE_SDL3 -DCIMGUI_USE_SDL3Renderer -DCIMGUI_USE_SDLGPU3 $(pkg-config --cflags sdl3) $cimgui_cflags"
    cimgui_impl_ldflags="$(pkg-config --libs sdl3) $cimgui_ldflags"

    if [ ! -x "$build_dir/ImGuiImplSDL3.so" ]; then
        if [ ! -d "{{ src_dir }}/cimgui_impl" ]; then
            just git-clone https://github.com/HexaEngine/cimgui_impl main
            (cd "{{ src_dir }}/cimgui_impl" && git checkout 7a459f54179587dc923749fed44ae34f78c370d3 && git submodule update --init --recursive)
        fi
        cd "{{ src_dir }}/cimgui_impl"
        "{{ gcc }}" \
        -o "$build_dir/ImGuiImplSDL3.so" \
        -Iimgui -Iimgui/backends -Iimgui/misc/freetype -Isrc -Iinclude \
        $cimgui_impl_cflags \
        src/cimgui_impl_{core,sdl3,sdl3renderer,sdlgpu3}.cpp \
        imgui/backends/imgui_impl_{sdl3,sdlrenderer3,sdlgpu3}.cpp \
        imgui/imgui{,_tables,_widgets,_draw,_demo}.cpp \
        imgui/misc/freetype/imgui_freetype.cpp \
        $cimgui_impl_ldflags
    fi

get-config-value name key:
    #!/usr/bin/env ruby
    require 'json'
    puts JSON.parse(File.read("{{ config_file }}"))["{{ name }}"]["{{ key }}"].to_s

clean:
    rm -rf *.AppImage *.zsync tools appdir src .cache output

[private]
@git-clone url branch="main" extra-args="" dest-name="":
    mkdir -p "{{ src_dir }}"
    echo "Cloning {{ url }}..."
    cd "{{ src_dir }}" && "{{ git }}" clone -q "{{ url }}" --single-branch --branch "{{ branch }}" {{ extra-args }} {{ dest-name }}
