set shell := ["bash", "-c"]

wget := require("wget")
dpkg_query := require("dpkg-query")
ldd := require("ldd")
git := require("git")
tool_dir := absolute_path("tools")
appimagetool := tool_dir + "/appimagetool"
aria2c := tool_dir + "/aria2c"
busybox := tool_dir + "/busybox"
config_file := absolute_path("config.json")
cache_dir := absolute_path(".cache")

@default:
    just --list

create-appimage config-name="xivlauncher": download-aria2c download-appimagetool download-busybox (download config-name)
    #!/usr/bin/env ruby
    require "fileutils"; include FileUtils
    require "pathname"

    CONFIG_NAME = "{{ config-name }}"

    class String
      def relative_to(resolve)
        Pathname.new(self).relative_path_from(resolve).to_s
      end
    end

    def gcv(key)
      `just get-config-value #{CONFIG_NAME} #{key}`.strip
    end

    XIVLAUNCHER_EXEC_NAME = gcv("executable")
    XIVLAUNCHER_VERSION = gcv("version")
    XIVLAUNCHER_SOURCE = gcv("src")
    XIVLAUNCHER_NAME = gcv("name")
    XIVLAUNCHER_DESC = gcv("description")
    XIVLAUNCHER_UPDATE_URL = gcv("update_url")

    APPDIR = File.join(Dir.pwd, "appdir", XIVLAUNCHER_EXEC_NAME)
    INSTALL_PATH = File.join(APPDIR, "opt", XIVLAUNCHER_EXEC_NAME)
    DESKTOP_FILE_PATH = File.join(APPDIR, "usr", "share", "applications", "#{XIVLAUNCHER_EXEC_NAME}.desktop")
    ICON_PATH = File.join(APPDIR, "usr", "share", "icons", "#{XIVLAUNCHER_EXEC_NAME}.png")
    OUTPUT_DIR = File.join(Dir.pwd, "output"); mkdir_p OUTPUT_DIR

    BINDIR = File.join(APPDIR, "usr", "bin")
    EXECUTABLE_INSTALL_PATH = File.join(APPDIR, "AppRun") #File.join(BINDIR, XIVLAUNCHER_EXEC_NAME)
    BUSYBOX_INSTALL_PATH = File.join(BINDIR, "busybox")

    UPDATE_DATA = "gh-releases-zsync|spiteful-fox|xivlauncher-appimage|latest|#{XIVLAUNCHER_NAME}-x86_64.AppImage.zsync"

    mkdir_p File.join(Dir.pwd, "appdir")
    cp_r "AppDir.template", APPDIR
    cp_r File.join(Dir.pwd, "src", "{{ config-name }}"), INSTALL_PATH
    cp File.join("resources", "xivlauncher.png"), ICON_PATH
    cp "{{ aria2c }}", BINDIR

    cp "{{ busybox }}", BUSYBOX_INSTALL_PATH
    `"#{BUSYBOX_INSTALL_PATH}" --list`.split("\n").each{|e| ln_sf BUSYBOX_INSTALL_PATH.relative_to(BINDIR), File.join(BINDIR, e.strip)}


    desktop_file = File.read(File.join("resources", "xivlauncher.desktop")) % {
      name: XIVLAUNCHER_NAME,
      description: XIVLAUNCHER_DESC,
      executable: XIVLAUNCHER_EXEC_NAME,
      appimage_version: XIVLAUNCHER_VERSION + " (#{`"{{ git }}" describe --tags`.strip})"
    }
    File.write(DESKTOP_FILE_PATH, desktop_file)

    executable = File.read(File.join("resources", "xivlauncher.sh")) % {executable: XIVLAUNCHER_EXEC_NAME}
    File.write(EXECUTABLE_INSTALL_PATH, executable)
    chmod "+x", EXECUTABLE_INSTALL_PATH

    [File.join(INSTALL_PATH, "XIVLauncher.Core"), Dir["#{INSTALL_PATH}/**/*.so"]].flatten.each do |obj|
      `just copy-dependencies "#{obj}" #{XIVLAUNCHER_EXEC_NAME}`
      chmod_R "+x", File.join(APPDIR, "usr", "lib")
    end

    ["libjxr0", "libsdl2-2.0-0", "libsecret-1-0", "libicu-dev"].each{|l| `just copy-package-libraries #{l} #{XIVLAUNCHER_EXEC_NAME}`}


    ln_sf DESKTOP_FILE_PATH.relative_to(APPDIR), File.join(APPDIR, "#{XIVLAUNCHER_EXEC_NAME}.desktop")
    ln_sf ICON_PATH.relative_to(APPDIR), File.join(APPDIR, "#{XIVLAUNCHER_EXEC_NAME}.png")

    `"{{ appimagetool }}.d/AppRun" -u "#{UPDATE_DATA}" "#{APPDIR}" "#{File.join(OUTPUT_DIR, XIVLAUNCHER_NAME + "-{{ arch() }}.AppImage")}"`
    Dir["*.zsync"].each{|f|mv f, OUTPUT_DIR}

copy-dependencies source-object config-name:
    #!/usr/bin/env ruby
    require "fileutils"; include FileUtils

    LIBDIR = File.join(Dir.pwd, "appdir", "{{ config-name }}", "usr", "lib")
    mkdir_p LIBDIR
    SEARCHED_FILES = []
    EXCLUDED_LIBRARIES = [
      ["c", "stdc++", "dl", "rt", "pthread", "m", "gcc_s"],
      ["wayland-client", "wayland-cursor", "wayland-egl", "wayland-server"],
      ["xcb", "xkbcommon", "X11", "X11-xcb", "Xau", "Xcursor", "Xdmcp", "Xext", "Xfixes", "Xi", "Xrandr", "Xrender", "Xss"],
      ["drm"]
    ].flatten.map{|i|"lib"+i}

    def get_deps(src)
      objects = []
      return objects if SEARCHED_FILES.include?(src)
      results = `{{ ldd }} "#{src}"`.split("\n").map{|s|s.strip}
      results.each do |r|
        matchdata = /^(.+) => (.+) \(0x[{{ HEXLOWER }}]+\)$/.match(r)
        if matchdata
          lib = matchdata.captures[1]
          objects << lib
        end
      end
      SEARCHED_FILES << src
      objects.each do |obj|
        objects |= get_deps(obj)
      end
      objects
    end

    get_deps("{{ source-object }}").each do |lib|
      destination = File.join(LIBDIR, File.basename(lib))
      exc = !EXCLUDED_LIBRARIES.select{|i| File.basename(lib).split(".")[0] == i}.empty?
      unless File.exist?(destination) || exc
        cp lib, destination
      end
    end

copy-package-libraries package-name config-name:
    #!/usr/bin/env ruby
    require "fileutils"; include FileUtils

    LIBDIR = File.join(Dir.pwd, "appdir", "{{ config-name }}", "usr", "lib")

    objects = []
    `{{ dpkg_query }} -L {{ package-name }}`.each_line do |line|
      matchdata = /^(.+\.so(\.\d)*)$/.match(line.strip)
      if matchdata
        objects << matchdata.captures[0]
      end
    end
    objects.each do |obj|
      cp "#{obj}", LIBDIR
      `just copy-dependencies "#{obj}" {{ config-name }}`
    end

download config-name:
    #!/usr/bin/env ruby
    require 'fileutils'; include FileUtils

    mkdir_p "{{ cache_dir }}"
    mkdir_p "{{ absolute_path('src') }}"
    bin_extract_dir = File.join("src", `just get-config-value {{ config-name }} executable`.strip)
    mkdir_p bin_extract_dir
    src = `just get-config-value {{ config-name }} src`.strip % {version: `just get-config-value {{ config-name }} version`.strip}
    archive_name = File.basename(src)
    dest = File.join("{{ cache_dir }}", `just get-config-value {{ config-name }} executable`.strip + ".tar.gz")
    dest_dir = dest.sub(".tar.gz", "")
    if !File.exist?(dest)
      `"{{ wget }}" -O #{dest} #{src}`
    end
    if !File.exist?(File.join(bin_extract_dir, "XIVLauncher.Core"))
      `tar -xzf "#{dest}" -C "#{bin_extract_dir}"`
    end

download-appimagetool:
    #!/usr/bin/env bash
    mkdir -p tools

    if [ ! -f "{{ appimagetool }}" ]; then
        "{{ wget }}" "https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-{{ arch() }}.AppImage" -O "{{ tool_dir }}/appimagetool"
        chmod +x "{{ tool_dir }}/appimagetool"
    fi

    if [ ! -d "{{ appimagetool }}.d" ]; then
        (cd {{ tool_dir }} && "{{ appimagetool }}" --appimage-extract)
        mv "{{ tool_dir }}/squashfs-root" "{{ tool_dir }}/appimagetool.d"
    fi

download-aria2c:
    #!/usr/bin/env bash
    mkdir -p tools

    if [ ! -f "{{ aria2c }}" ]; then
        "{{ wget }}" -qO- "https://github.com/abcfy2/aria2-static-build/releases/download/continuous/aria2-x86_64-linux-musl_static.zip" | zcat > "{{ aria2c }}"
        chmod +x "{{ aria2c }}"
    fi

download-busybox:
    #!/usr/bin/env bash
    mkdir -p tools

    if [ ! -f "{{ busybox }}" ]; then
        "{{ wget }}" https://github.com/ruanformigoni/busybox-static-musl/releases/download/7e2c5b6/busybox-x86_64 -O "{{ busybox }}"
        chmod +x "{{ busybox }}"
    fi

get-config-value name key:
    #!/usr/bin/env ruby
    require 'json'
    puts JSON.parse(File.read("{{ config_file }}"))["{{ name }}"]["{{ key }}"].to_s

clean:
    rm -rf *.AppImage *.zsync tools appdir src .cache output
