name: Build AppImages

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # Need full history for tagging

            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y podman git ruby
                  curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin

            - name: Set up Git user
              run: |
                  git config --global user.name "GitHub Actions"
                  git config --global user.email "actions@github.com"

            - name: Tag current commit
              id: tag
              run: |
                  TAG=$(just tag-commit)
                  echo "tag=$TAG" >> $GITHUB_OUTPUT
                  echo "Created tag: $TAG"

            - name: Push tag to GitHub
              run: |
                  git push origin ${{ steps.tag.outputs.tag }}

            - name: Build container image
              run: just build-image

            - name: Build xivlauncher AppImage
              run: just build xivlauncher

            - name: Build xivlauncher-rb AppImage
              run: just build xivlauncher-rb

            - name: Upload AppImage artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: appimages-${{ steps.tag.outputs.tag }}
                  path: output/
                  retention-days: 30
